### ISSUE TITLE
Intera behavior editor with simulator

### ISSUE THREAD

**Issue by dattachandan** [RethinkRobotics/sawyer_simulator#41]
Hi,
Had a quick chat with Dr Brooks at ICRA 2018 today and thought will drop in a line here. We have baxters in our lab but no sawyer. However, I am quite keen to try out the intera studio editor in ROS+gazebo(http://mfg.rethinkrobotics.com/intera/Behavior_Editor_Overview). wondering if that is possible?

**Comment by IanTheEngineer** [comment]
@dattachandan thanks for your input on this, I will make sure your feature request is documented internally. Although, as this repo is for the researchers SDK, I’m going to close this issue.

**Comment by dattachandan** [comment]
@IanTheEngineer thanks for the update - is there any plans to integrate with any open simulator or the upcoming Nvidia Issac sim?

Is there a way for me to tryout Intera Studio editor without purchasing Sawyer? We have 2 baxters
